// 回声岛 Echo Island — 关卡内容
// 每个岛 = 七年级一个常见话题。words: [英文, 中文, 图], sents: [英文, 中文], dlgs: [对方说, 正确回答, [干扰项, 干扰项]]
window.WORLDS = [
  {
    name: '你好岛', en: 'Hello!', icon: '👋', color: '#FF8A5B',
    boss: { emoji: '🦜', name: '鹦鹉船长', hello: "Hello! I'm Captain Polly. Can you talk to me?" },
    words: [
      ['hello', '你好', '👋'], ['good morning', '早上好', '🌅'], ['good afternoon', '下午好', '🌤️'],
      ['good evening', '晚上好', '🌙'], ['goodbye', '再见', '🚶'], ['name', '名字', '🏷️'],
      ['friend', '朋友', '🧑‍🤝‍🧑'], ['teacher', '老师', '👩‍🏫'], ['student', '学生', '🧑‍🎓'],
      ['classmate', '同学', '👫'], ['thank you', '谢谢', '🙏'], ['sorry', '对不起', '🙇'],
    ],
    sents: [
      ["What's your name?", '你叫什么名字？'], ['My name is Li Ming.', '我的名字是李明。'],
      ['Nice to meet you.', '很高兴认识你。'], ['How are you?', '你好吗？'],
      ["I'm fine, thank you.", '我很好，谢谢。'], ['This is my friend Tom.', '这是我的朋友汤姆。'],
      ['Good morning, Ms Wang!', '王老师，早上好！'], ['See you tomorrow.', '明天见。'],
    ],
    dlgs: [
      ["Hello! What's your name?", 'My name is Lucy.', ["I'm twelve.", "It's a pen."]],
      ['How are you?', "I'm fine, thanks.", ["I'm Tom.", 'Yes, it is.']],
      ['Nice to meet you.', 'Nice to meet you, too.', ["You're welcome.", 'Good night.']],
      ['Good morning!', 'Good morning!', ['Good night!', 'Thank you!']],
      ['Thank you!', "You're welcome.", ["I'm sorry.", 'Me too.']],
      ['Goodbye!', 'See you!', ['Hello!', 'How are you?']],
      ['Are you a new student?', 'Yes, I am.', ['Yes, it is.', "No, he isn't."]],
    ],
  },
  {
    name: '彩色文具岛', en: 'Keep Tidy!', icon: '🎨', color: '#F2B705',
    boss: { emoji: '🦀', name: '彩虹蟹', hello: "I'm Crabby the rainbow crab. What colour is my shell?" },
    words: [
      ['pen', '钢笔', '🖊️'], ['pencil', '铅笔', '✏️'], ['ruler', '尺子', '📏'], ['book', '书', '📘'],
      ['schoolbag', '书包', '🎒'], ['key', '钥匙', '🔑'], ['cap', '帽子', '🧢'], ['red', '红色', '🔴'],
      ['blue', '蓝色', '🔵'], ['green', '绿色', '🟢'], ['yellow', '黄色', '🟡'], ['black', '黑色', '⚫'],
      ['white', '白色', '⚪'],
    ],
    sents: [
      ["What's this in English?", '这个用英语怎么说？'], ["It's a ruler.", '它是一把尺子。'],
      ['What colour is it?', '它是什么颜色？'], ["It's yellow.", '它是黄色的。'],
      ['Is this your pencil?', '这是你的铅笔吗？'], ['Where is my schoolbag?', '我的书包在哪里？'],
      ['Keep your desk tidy.', '保持你的书桌整洁。'], ['The key is in the bag.', '钥匙在包里。'],
    ],
    dlgs: [
      ["What's this in English?", "It's a key.", ["It's red.", "I'm fine."]],
      ['What colour is your bag?', "It's blue.", ["It's a bag.", 'Yes, it is.']],
      ['Is this your pen?', 'Yes, it is.', ['Yes, I am.', "It's black."]],
      ['Where is my ruler?', "It's on the desk.", ["It's green.", "It's a ruler."]],
      ['Is that your cap?', "No, it isn't.", ["No, I'm not.", "It's a cap."]],
      ['What colour is the pencil?', "It's green.", ["It's a pencil.", 'Yes, it is.']],
    ],
  },
  {
    name: '温馨家庭岛', en: "We're Family!", icon: '🏡', color: '#E85D75',
    boss: { emoji: '🐢', name: '海龟奶奶', hello: "Hello, dear. I'm Granny Turtle. Tell me about your family." },
    words: [
      ['family', '家庭', '👨‍👩‍👧'], ['father', '父亲', '👨'], ['mother', '母亲', '👩'],
      ['grandfather', '祖父', '👴'], ['grandmother', '祖母', '👵'], ['brother', '兄弟', '👦'],
      ['sister', '姐妹', '👧'], ['uncle', '叔叔', '🧔'], ['aunt', '阿姨', '👩‍🦰'],
      ['cousin', '堂(表)兄弟姐妹', '🧒'], ['baby', '婴儿', '👶'], ['photo', '照片', '📷'],
    ],
    sents: [
      ['This is my family.', '这是我的家人。'], ['Who is she?', '她是谁？'],
      ['She is my mother.', '她是我的妈妈。'], ['These are my grandparents.', '这些是我的祖父母。'],
      ['I have a little brother.', '我有一个弟弟。'], ['Those are my cousins.', '那些是我的表兄弟姐妹。'],
      ['My father is a doctor.', '我爸爸是一名医生。'],
      ['How many people are there in your family?', '你家有几口人？'],
    ],
    dlgs: [
      ['Who is he?', "He's my father.", ["She's my aunt.", "I'm fine."]],
      ['Is this your sister?', 'Yes, she is.', ['Yes, he is.', 'Yes, it is.']],
      ['How many people are there in your family?', 'There are four.', ["I'm twelve.", "It's my family."]],
      ['What does your mother do?', "She's a teacher.", ["She's forty.", "She's my mother."]],
      ['Do you have a brother?', "No, I don't.", ["No, he isn't.", "No, I'm not."]],
      ['Are these your parents?', 'Yes, they are.', ['Yes, it is.', 'Yes, I do.']],
    ],
  },
  {
    name: '校园岛', en: 'My School', icon: '🏫', color: '#3A86FF',
    boss: { emoji: '🦉', name: '猫头鹰校长', hello: "Welcome! I'm Principal Owl. Let me test you." },
    words: [
      ['classroom', '教室', '🏫'], ['library', '图书馆', '📚'], ['playground', '操场', '🛝'],
      ['dining hall', '食堂', '🍽️'], ['gym', '体育馆', '🏀'], ['lab', '实验室', '🔬'],
      ['office', '办公室', '🗄️'], ['building', '大楼', '🏢'], ['computer', '电脑', '💻'],
      ['chair', '椅子', '🪑'], ['clock', '钟', '🕒'], ['map', '地图', '🗺️'],
    ],
    sents: [
      ['Where is the library?', '图书馆在哪里？'], ["It's next to the dining hall.", '它在食堂旁边。'],
      ['There is a big playground in our school.', '我们学校有一个大操场。'],
      ['Our classroom is on the second floor.', '我们的教室在二楼。'],
      ['The gym is across from the library.', '体育馆在图书馆对面。'],
      ['There are forty desks in my classroom.', '我的教室里有四十张课桌。'],
      ['Welcome to my school!', '欢迎来到我的学校！'], ['Is there a lab in your school?', '你的学校有实验室吗？'],
    ],
    dlgs: [
      ['Where is the gym?', "It's behind the library.", ["It's big.", 'Yes, there is.']],
      ['Is there a computer room in your school?', 'Yes, there is.', ['Yes, it is.', 'Yes, I am.']],
      ["What's your favourite place in the school?", 'The library.', ['At seven.', 'My teacher.']],
      ['Which floor is your classroom on?', 'The third floor.', ['Room three.', "It's clean."]],
      ['How many students are there in your class?', 'There are forty-five.', ["I'm in Class Five.", "It's big."]],
      ['Excuse me, where is the office?', "It's next to the hall.", ["You're welcome.", "It's nine o'clock."]],
    ],
  },
  {
    name: '学科岛', en: 'Favourite Subjects', icon: '📐', color: '#8E6CEF',
    boss: { emoji: '🐙', name: '八爪博士', hello: "I'm Doctor Octo. I teach eight subjects at the same time!" },
    words: [
      ['English', '英语', '🔤'], ['Chinese', '语文', '🀄'], ['maths', '数学', '➗'],
      ['science', '科学', '🧪'], ['history', '历史', '🏺'], ['geography', '地理', '🌏'],
      ['music', '音乐', '🎵'], ['art', '美术', '🎨'], ['PE', '体育', '🏃'],
      ['biology', '生物', '🌱'], ['interesting', '有趣的', '🤩'], ['boring', '无聊的', '🥱'],
    ],
    sents: [
      ["What's your favourite subject?", '你最喜欢的科目是什么？'],
      ['My favourite subject is science.', '我最喜欢的科目是科学。'],
      ['Why do you like music?', '你为什么喜欢音乐？'], ["Because it's relaxing.", '因为它令人放松。'],
      ['I think maths is difficult.', '我认为数学很难。'], ['We have art on Friday.', '我们周五有美术课。'],
      ['Who is your English teacher?', '你的英语老师是谁？'], ['History is interesting.', '历史很有趣。'],
    ],
    dlgs: [
      ["What's your favourite subject?", 'I like PE best.', ["It's Monday.", 'My teacher is Mr Li.']],
      ['Why do you like geography?', "Because it's fun.", ['Yes, I do.', 'On Tuesday.']],
      ['When do you have music?', 'On Wednesday.', ["It's interesting.", 'My music teacher.']],
      ['Do you like maths?', 'Yes, I do.', ['Yes, it is.', 'Yes, I am.']],
      ['How many subjects do you have?', 'We have nine.', ["I'm nine.", "It's my subject."]],
      ['What do you think of history?', "It's interesting.", ["It's on Friday.", 'I think so.']],
    ],
  },
  {
    name: '社团岛', en: 'Fun Clubs', icon: '🎸', color: '#FF5E9C',
    boss: { emoji: '🦩', name: '火烈鸟乐手', hello: "Hi! I'm Flo. I can sing, dance and play the drums. What can you do?" },
    words: [
      ['club', '社团', '🎪'], ['sing', '唱歌', '🎤'], ['dance', '跳舞', '💃'], ['swim', '游泳', '🏊'],
      ['draw', '画画', '🖍️'], ['play chess', '下国际象棋', '♟️'], ['play the guitar', '弹吉他', '🎸'],
      ['play the piano', '弹钢琴', '🎹'], ['play the drums', '打鼓', '🥁'], ['speak English', '说英语', '🗣️'],
      ['cook', '烹饪', '🍳'], ['join', '加入', '🙋'],
    ],
    sents: [
      ['Can you swim?', '你会游泳吗？'], ['I can play the guitar.', '我会弹吉他。'],
      ['What club do you want to join?', '你想加入什么社团？'], ['I want to join the music club.', '我想加入音乐社。'],
      ['She can dance very well.', '她跳舞跳得很好。'], ['Join our chess club!', '加入我们的国际象棋社吧！'],
      ["He can't play the piano.", '他不会弹钢琴。'], ['We have fun in the art club.', '我们在美术社玩得很开心。'],
    ],
    dlgs: [
      ['Can you sing?', 'Yes, I can.', ['Yes, I do.', 'Yes, it is.']],
      ['What club do you want to join?', 'The swimming club.', ['I can swim.', 'On Monday.']],
      ['Can your brother play the drums?', "No, he can't.", ["No, I can't.", "No, he isn't."]],
      ['What can you do?', 'I can draw.', ["I'm in the club.", 'Yes, I can.']],
      ['Do you want to join the chess club?', 'Sure! I love chess.', ["It's a chess club.", "I'm Tom."]],
      ['Can you speak English?', 'Yes, a little.', ['Yes, it is English.', 'Thanks a lot.']],
    ],
  },
  {
    name: '作息岛', en: 'A Day in the Life', icon: '⏰', color: '#14A38B',
    boss: { emoji: '🐓', name: '闹钟公鸡', hello: "Cock-a-doodle-doo! I'm Rooster Rex. Wake up and answer me!" },
    words: [
      ['get up', '起床', '🛏️'], ['brush teeth', '刷牙', '🪥'], ['shower', '淋浴', '🚿'],
      ['breakfast', '早餐', '🥣'], ['lunch', '午餐', '🍱'], ['dinner', '晚餐', '🍲'],
      ['homework', '家庭作业', '📝'], ['go to school', '去上学', '🚌'], ['go to bed', '上床睡觉', '😴'],
      ["o'clock", '……点钟', '🕗'], ['always', '总是', '🔁'], ['never', '从不', '🚫'],
    ],
    sents: [
      ['What time do you usually get up?', '你通常几点起床？'],
      ['I usually get up at six thirty.', '我通常六点半起床。'],
      ['I always eat breakfast at seven.', '我总是七点吃早餐。'],
      ["School starts at eight o'clock.", '学校八点开始上课。'],
      ['I do my homework after dinner.', '我晚饭后做作业。'],
      ['I go to bed at half past nine.', '我九点半睡觉。'],
      ['When do you go to school?', '你什么时候去上学？'],
      ['He is never late for school.', '他上学从不迟到。'],
    ],
    dlgs: [
      ['What time do you get up?', "At six o'clock.", ['For six hours.', "It's Monday."]],
      ['When do you do your homework?', 'After dinner.', ['Yes, I do.', 'My maths homework.']],
      ['How do you go to school?', 'I take the bus.', ['At seven.', 'I like school.']],
      ['What time is it now?', "It's half past seven.", ["It's Monday.", "I'm at school."]],
      ['Do you take a shower in the morning?', 'No, in the evening.', ["No, it isn't.", 'Yes, I am.']],
      ['What do you usually have for breakfast?', 'Milk and eggs.', ['At seven thirty.', 'In the kitchen.']],
    ],
  },
  {
    name: '生日派对岛', en: 'Happy Birthday!', icon: '🎂', color: '#F77F00',
    boss: { emoji: '🐡', name: '河豚派对王', hello: "It's my party! I'm Puffy. Answer me and get some cake!" },
    words: [
      ['birthday', '生日', '🎂'], ['cake', '蛋糕', '🍰'], ['party', '派对', '🎉'], ['gift', '礼物', '🎁'],
      ['candle', '蜡烛', '🕯️'], ['balloon', '气球', '🎈'], ['noodles', '面条', '🍜'], ['egg', '鸡蛋', '🥚'],
      ['juice', '果汁', '🧃'], ['January', '一月', '🧣'], ['May', '五月', '🌸'], ['October', '十月', '🎃'],
      ['month', '月份', '🗓️'],
    ],
    sents: [
      ['When is your birthday?', '你的生日是什么时候？'], ['My birthday is on May 2nd.', '我的生日是5月2日。'],
      ['Happy birthday to you!', '祝你生日快乐！'], ['How old are you?', '你多大了？'],
      ["I'm thirteen years old.", '我十三岁了。'], ["Let's have a party!", '我们开个派对吧！'],
      ['Make a wish!', '许个愿吧！'], ['This gift is for you.', '这份礼物是给你的。'],
    ],
    dlgs: [
      ['Happy birthday!', 'Thank you!', ['You too!', 'Me too!']],
      ['How old are you?', "I'm thirteen.", ["I'm fine.", 'In May.']],
      ['When is your birthday?', "It's on October 5th.", ["I'm twelve.", "It's a cake."]],
      ['This gift is for you.', 'Thank you so much!', ["You're welcome.", 'Yes, it is.']],
      ['What do you want for your birthday?', 'A new bike.', ['On Sunday.', "I'm thirteen."]],
      ['Would you like some cake?', 'Yes, please.', ["No, it isn't.", 'Happy birthday!']],
    ],
  },
  {
    name: '动物岛', en: 'Animal Friends', icon: '🐼', color: '#2E9E4F',
    boss: { emoji: '🐊', name: '鳄鱼巡查员', hello: "Snap snap! I'm Croc. Do you really know animals?" },
    words: [
      ['panda', '熊猫', '🐼'], ['elephant', '大象', '🐘'], ['tiger', '老虎', '🐯'], ['lion', '狮子', '🦁'],
      ['giraffe', '长颈鹿', '🦒'], ['monkey', '猴子', '🐒'], ['koala', '考拉', '🐨'], ['dolphin', '海豚', '🐬'],
      ['penguin', '企鹅', '🐧'], ['zebra', '斑马', '🦓'], ['cute', '可爱的', '🥰'], ['smart', '聪明的', '🧠'],
    ],
    sents: [
      ["Let's see the pandas first.", '我们先去看熊猫吧。'], ['Why do you like koalas?', '你为什么喜欢考拉？'],
      ["Because they're very cute.", '因为它们非常可爱。'], ['Elephants are smart animals.', '大象是聪明的动物。'],
      ['Where are lions from?', '狮子来自哪里？'], ["They're from Africa.", '它们来自非洲。'],
      ['Dolphins can swim very fast.', '海豚能游得非常快。'], ['We must save the animals.', '我们必须保护动物。'],
    ],
    dlgs: [
      ['What animal do you like?', 'I like pandas.', ["It's a zoo.", 'Yes, I do.']],
      ['Why do you like tigers?', "Because they're strong.", ["They're from Asia.", 'Yes, they are.']],
      ['Where are koalas from?', "They're from Australia.", ["They're cute.", 'They eat leaves.']],
      ['Are giraffes tall?', 'Yes, they are.', ['Yes, it is.', 'Yes, they do.']],
      ['What do pandas eat?', 'They eat bamboo.', ["They're black and white.", "They're sleeping."]],
      ["Let's see the monkeys.", 'Great idea!', ["You're welcome.", "They're monkeys."]],
    ],
  },
  {
    name: '规则岛', en: 'No Rules, No Order', icon: '🚦', color: '#D62828',
    boss: { emoji: '🦈', name: '鲨鱼纪律官', hello: "I'm Sharky. I make the rules here. Do you know them?" },
    words: [
      ['rule', '规则', '📜'], ['late', '迟到的', '🐌'], ['quiet', '安静的', '🤫'], ['run', '跑', '🏃'],
      ['fight', '打架', '🥊'], ['listen', '听', '👂'], ['wear', '穿', '👕'], ['uniform', '校服', '🧥'],
      ['hallway', '走廊', '🚪'], ['phone', '手机', '📱'], ['clean', '打扫', '🧹'], ['wait', '等待', '⏳'],
    ],
    sents: [
      ["Don't run in the hallways.", '不要在走廊里奔跑。'], ["Don't be late for class.", '上课不要迟到。'],
      ['We must wear a uniform.', '我们必须穿校服。'], ["We can't eat in the classroom.", '我们不能在教室里吃东西。'],
      ['Listen to the teacher carefully.', '认真听老师讲课。'], ['Keep quiet in the library.', '在图书馆保持安静。'],
      ['Do we have to clean the classroom?', '我们必须打扫教室吗？'], ['No rules, no order.', '没有规矩，不成方圆。'],
    ],
    dlgs: [
      ['Can we bring phones to school?', "No, we can't.", ["No, we don't.", 'Yes, it is.']],
      ['Do you have to wear a uniform?', 'Yes, we do.', ['Yes, we are.', 'Yes, it does.']],
      ['What are the rules in your school?', "We can't be late.", ['We are late.', "It's a rule."]],
      ['Can we eat in the library?', 'No. We must eat in the dining hall.', ['Yes, we eat.', "It's a library."]],
      ["Sorry, I'm late.", "It's OK. Don't be late again.", ["You're welcome.", 'Nice to meet you.']],
      ['What do you have to do at home?', 'I have to wash the dishes.', ['I have a home.', 'At home.']],
    ],
  },
  {
    name: '运动美食岛', en: 'Keep Fit, Eat Well', icon: '🥗', color: '#6A994E',
    boss: { emoji: '🦭', name: '海狮教练', hello: "I'm Coach Seal. Healthy body, happy mind! Ready?" },
    words: [
      ['basketball', '篮球', '🏀'], ['football', '足球', '⚽'], ['ping-pong', '乒乓球', '🏓'],
      ['exercise', '锻炼', '🏋️'], ['healthy', '健康的', '💪'], ['vegetables', '蔬菜', '🥦'],
      ['fruit', '水果', '🍎'], ['rice', '米饭', '🍚'], ['beef', '牛肉', '🥩'], ['chicken', '鸡肉', '🍗'],
      ['dumplings', '饺子', '🥟'], ['milk', '牛奶', '🥛'], ['hamburger', '汉堡', '🍔'],
    ],
    sents: [
      ["Let's play basketball after school.", '放学后我们打篮球吧。'], ['How often do you exercise?', '你多久锻炼一次？'],
      ['I exercise three times a week.', '我每周锻炼三次。'], ['Eat more vegetables and fruit.', '多吃蔬菜和水果。'],
      ['What would you like to eat?', '你想吃什么？'], ["I'd like some beef noodles.", '我想要一些牛肉面。'],
      ['Hamburgers are not healthy.', '汉堡不健康。'], ['Drink milk every day.', '每天喝牛奶。'],
    ],
    dlgs: [
      ['What would you like?', "I'd like some dumplings, please.", ['I like sports.', 'Yes, I would.']],
      ['How often do you play football?', 'Twice a week.', ['For two hours.', 'On the playground.']],
      ['Do you like vegetables?', 'Yes, I love them.', ['Yes, it is.', 'Yes, I am.']],
      ['What size bowl would you like?', 'A large bowl, please.', ["I'd like beef.", "It's twenty yuan."]],
      ['Is ice cream healthy?', 'No, not really.', ["No, I don't.", 'Yes, please.']],
      ["Let's play ping-pong!", 'That sounds good.', ["It's a ball.", "You're welcome."]],
    ],
  },
  {
    name: '天气岛', en: 'Rain or Shine', icon: '🌦️', color: '#4895EF',
    boss: { emoji: '🐳', name: '天气鲸', hello: "Hello from the sea! I'm Whaley. How's the weather up there?" },
    words: [
      ['sunny', '晴朗的', '☀️'], ['rainy', '下雨的', '🌧️'], ['cloudy', '多云的', '☁️'], ['windy', '有风的', '🌬️'],
      ['snowy', '下雪的', '❄️'], ['hot', '热的', '🥵'], ['cold', '冷的', '🥶'], ['warm', '温暖的', '🌡️'],
      ['weather', '天气', '🌦️'], ['umbrella', '雨伞', '☂️'], ['watch TV', '看电视', '📺'], ['read', '读书', '📖'],
    ],
    sents: [
      ["How's the weather today?", '今天天气怎么样？'], ["It's sunny and warm.", '天气晴朗温暖。'],
      ['What are you doing?', '你在做什么？'], ["I'm watching TV.", '我在看电视。'],
      ["It's raining in Beijing.", '北京正在下雨。'], ['Take an umbrella with you.', '带上雨伞。'],
      ['My mom is cooking dinner now.', '我妈妈现在正在做晚饭。'],
      ["What's the weather like in Harbin?", '哈尔滨天气怎么样？'],
    ],
    dlgs: [
      ["How's the weather in Shanghai?", "It's cloudy.", ["It's Monday.", "I'm reading."]],
      ['What are you doing?', "I'm doing my homework.", ['I do my homework.', "It's sunny."]],
      ['Is it cold there?', "Yes, it's snowing.", ['Yes, I am.', "It's my coat."]],
      ["What's your father doing?", "He's reading a newspaper.", ['He reads.', "He's my father."]],
      ["It's raining. Let's stay at home.", "OK. Let's watch a movie.", ["It's sunny.", 'Nice to meet you.']],
      ["How's it going?", 'Not bad, thanks.', ["It's going to school.", "It's cold."]],
    ],
  },
  {
    name: '回忆岛', en: 'A Day to Remember', icon: '📸', color: '#9D4EDD',
    boss: { emoji: '🐉', name: '回忆巨龙', hello: "I am the Memory Dragon. Tell me about your past, if you dare!" },
    words: [
      ['went', '去了', '🚶'], ['visited', '参观了', '🏛️'], ['saw', '看见了', '👀'], ['ate', '吃了', '🍽️'],
      ['took photos', '拍了照片', '📸'], ['bought', '买了', '🛍️'], ['trip', '旅行', '🧳'],
      ['yesterday', '昨天', '⏪'], ['last weekend', '上周末', '📅'], ['farm', '农场', '🚜'],
      ['beach', '海滩', '🏖️'], ['fun', '有趣的', '🥳'],
    ],
    sents: [
      ['What did you do last weekend?', '你上周末做了什么？'], ['I visited my grandparents.', '我去看望了我的祖父母。'],
      ['How was your trip?', '你的旅行怎么样？'], ['It was great!', '棒极了！'],
      ['We went to the beach.', '我们去了海滩。'], ['I took a lot of photos.', '我拍了很多照片。'],
      ['Did you see any cows?', '你看到奶牛了吗？'], ['Yes, I did.', '是的，我看到了。'],
    ],
    dlgs: [
      ['What did you do yesterday?', 'I went to the museum.', ['I go to the museum.', 'It was yesterday.']],
      ['How was your weekend?', 'It was fun.', ['It is Sunday.', "It's on the weekend."]],
      ['Did you go to the farm?', 'Yes, I did.', ['Yes, I do.', 'Yes, it was.']],
      ['Where did you go on vacation?', 'I went to Hainan.', ['I go with my family.', 'It was sunny.']],
      ['What did you see there?', 'I saw many animals.', ['I see many animals.', 'It was great.']],
      ['Did you have a good time?', 'Yes, I had a great time.', ['Yes, I have.', "No, it isn't."]],
    ],
  },
];

// 对话动画：每个岛一段情景对话。set: 背景（见 cartoon.js），cast: [名字, 形象, 声音 f/m]，lines: [第几个角色, 英文, 中文]
window.SCENES = [
  {
    title: '开学第一天', place: '教室门口', bg: '🏫', set: 'gate',
    cast: [['Lily', '👧', 'f'], ['Tom', '👦', 'm']],
    lines: [
      [0, "Good morning! I'm Lily. What's your name?", '早上好！我是莉莉。你叫什么名字？'],
      [1, 'Hi, Lily. My name is Tom.', '你好，莉莉。我叫汤姆。'],
      [0, 'Nice to meet you, Tom.', '很高兴认识你，汤姆。'],
      [1, 'Nice to meet you, too. Are you in Class Five?', '我也很高兴认识你。你在五班吗？'],
      [0, 'Yes, I am. How about you?', '是的。你呢？'],
      [1, "Me too! We're classmates.", '我也是！我们是同学。'],
      [0, 'Great! See you in class.', '太好了！课上见。'],
      [1, 'See you!', '回头见！'],
    ],
  },
  {
    title: '这是谁的？', place: '教室里', bg: '🎒', set: 'classroom',
    cast: [['Tom', '👦', 'm'], ['Lily', '👧', 'f']],
    lines: [
      [0, 'Excuse me, Lily. Is this your pencil?', '打扰一下，莉莉。这是你的铅笔吗？'],
      [1, "No, it isn't. My pencil is yellow.", '不是。我的铅笔是黄色的。'],
      [0, "Oh. What's this in English?", '哦。这个用英语怎么说？'],
      [1, "It's a ruler. Is it yours?", '它是一把尺子。是你的吗？'],
      [0, 'Yes, it is. Thank you!', '是的。谢谢你！'],
      [1, "You're welcome. Keep your desk tidy!", '不客气。要保持书桌整洁哦！'],
      [0, 'OK, I will.', '好的，我会的。'],
    ],
  },
  {
    title: '看全家福', place: '莉莉家', bg: '📷', set: 'living',
    cast: [['Lily', '👧', 'f'], ['Tom', '👦', 'm']],
    lines: [
      [0, 'Tom, look! This is my family photo.', '汤姆，看！这是我的全家福。'],
      [1, 'Wow! Who is this man?', '哇！这个男人是谁？'],
      [0, "He's my father. He's a doctor.", '他是我爸爸。他是一名医生。'],
      [1, 'And who is the little girl?', '那这个小女孩是谁？'],
      [0, "She's my sister, Mary.", '她是我妹妹玛丽。'],
      [1, 'How many people are there in your family?', '你家有几口人？'],
      [0, 'There are five: my grandmother, my parents, my sister and me.', '五口人：我奶奶、我父母、我妹妹和我。'],
      [1, 'What a happy family!', '真是幸福的一家！'],
    ],
  },
  {
    title: '新同学问路', place: '校园里', bg: '🏫', set: 'campus',
    cast: [['Tom', '👦', 'm'], ['Lily', '👧', 'f']],
    lines: [
      [0, 'Excuse me, where is the library?', '打扰一下，图书馆在哪里？'],
      [1, "It's next to the dining hall.", '它在食堂旁边。'],
      [0, 'Is there a gym in our school?', '我们学校有体育馆吗？'],
      [1, "Yes, there is. It's across from the library.", '有的。它在图书馆对面。'],
      [0, 'Thanks! Our school is so big.', '谢谢！我们学校好大。'],
      [1, "Yes, it is. Come on, I'll show you around.", '是啊。来吧，我带你转转。'],
    ],
  },
  {
    title: '你最喜欢哪一科？', place: '课间', bg: '📐', set: 'classroom',
    cast: [['Lily', '👧', 'f'], ['Tom', '👦', 'm']],
    lines: [
      [0, "What's your favourite subject, Tom?", '汤姆，你最喜欢什么科目？'],
      [1, 'I like PE best.', '我最喜欢体育。'],
      [0, 'Why do you like PE?', '你为什么喜欢体育？'],
      [1, "Because it's fun and relaxing. What about you?", '因为它有趣又放松。你呢？'],
      [0, 'My favourite subject is science.', '我最喜欢的科目是科学。'],
      [1, 'Science? I think it is difficult.', '科学？我觉得它很难。'],
      [0, "No, it's interesting! We have science on Monday.", '不，它很有趣！我们周一有科学课。'],
    ],
  },
  {
    title: '加入社团', place: '社团招新', bg: '🎸', set: 'club',
    cast: [['Lily', '👧', 'f'], ['Tom', '👦', 'm']],
    lines: [
      [0, 'Tom, what club do you want to join?', '汤姆，你想加入什么社团？'],
      [1, 'I want to join the music club.', '我想加入音乐社。'],
      [0, 'Can you sing?', '你会唱歌吗？'],
      [1, "No, I can't. But I can play the guitar.", '我不会。但我会弹吉他。'],
      [0, "Cool! I can sing. Let's join the club together.", '酷！我会唱歌。我们一起加入吧。'],
      [1, 'Sounds great!', '好主意！'],
    ],
  },
  {
    title: '你几点起床？', place: '上学路上', bg: '⏰', set: 'street',
    cast: [['Tom', '👦', 'm'], ['Lily', '👧', 'f']],
    lines: [
      [0, 'What time do you usually get up, Lily?', '莉莉，你通常几点起床？'],
      [1, 'I usually get up at six thirty.', '我通常六点半起床。'],
      [0, "That's early! What do you do then?", '真早！然后做什么？'],
      [1, 'I brush my teeth and eat breakfast.', '我刷牙、吃早饭。'],
      [0, 'How do you go to school?', '你怎么去上学？'],
      [1, "I take the bus. School starts at eight o'clock.", '我坐公交车。学校八点开始上课。'],
      [0, 'I always get up late. I must get up early, too!', '我总是起得晚。我也得早点起床！'],
    ],
  },
  {
    title: '生日派对', place: '莉莉的生日会', bg: '🎂', set: 'party',
    cast: [['Tom', '👦', 'm'], ['Lily', '👧', 'f']],
    lines: [
      [0, 'Happy birthday, Lily! This gift is for you.', '生日快乐，莉莉！这是给你的礼物。'],
      [1, 'Thank you so much, Tom!', '太谢谢你了，汤姆！'],
      [0, 'How old are you today?', '你今天几岁了？'],
      [1, "I'm thirteen. When is your birthday?", '我十三岁了。你的生日是什么时候？'],
      [0, "It's on October 5th.", '在十月五日。'],
      [1, 'Would you like some cake?', '你想吃点蛋糕吗？'],
      [0, 'Yes, please. Make a wish!', '好的，谢谢。许个愿吧！'],
    ],
  },
  {
    title: '逛动物园', place: '动物园', bg: '🐼', set: 'zoo',
    cast: [['Lily', '👧', 'f'], ['Tom', '👦', 'm']],
    lines: [
      [0, "Let's see the pandas first.", '我们先去看熊猫吧。'],
      [1, 'Why do you like pandas?', '你为什么喜欢熊猫？'],
      [0, "Because they're very cute. What animal do you like?", '因为它们非常可爱。你喜欢什么动物？'],
      [1, "I like elephants. They're smart.", '我喜欢大象。它们很聪明。'],
      [0, 'Where are elephants from?', '大象来自哪里？'],
      [1, "They're from Africa and Asia.", '它们来自非洲和亚洲。'],
      [0, 'We must save the animals.', '我们必须保护动物。'],
    ],
  },
  {
    title: '别在走廊跑！', place: '学校走廊', bg: '🚦', set: 'hallway',
    cast: [['Ms Wang', '👩‍🏫', 'f'], ['Tom', '👦', 'm']],
    lines: [
      [0, "Tom, don't run in the hallways.", '汤姆，不要在走廊里跑。'],
      [1, "Sorry, Ms Wang. I'm late for class.", '对不起，王老师。我上课要迟到了。'],
      [0, "Don't be late again. And we can't eat in the classroom.", '不要再迟到了。还有，我们不能在教室里吃东西。'],
      [1, 'OK. Can we bring phones to school?', '好的。我们可以带手机来学校吗？'],
      [0, "No, you can't. Please follow the rules.", '不，不可以。请遵守规则。'],
      [1, 'Yes, Ms Wang.', '好的，王老师。'],
    ],
  },
  {
    title: '去面馆点餐', place: '面馆', bg: '🍜', set: 'shop',
    cast: [['Waiter', '🧑‍🍳', 'm'], ['Lily', '👧', 'f']],
    lines: [
      [0, 'Hello! What would you like?', '你好！你想要点什么？'],
      [1, "I'd like some beef noodles, please.", '我想要一些牛肉面。'],
      [0, 'What size bowl would you like?', '你要多大碗的？'],
      [1, 'A large bowl, please.', '请给我一大碗。'],
      [0, 'Would you like any vegetables?', '要加些蔬菜吗？'],
      [1, 'Yes, please. Vegetables are healthy.', '好的。蔬菜很健康。'],
    ],
  },
  {
    title: '打电话聊天气', place: '北京 ↔ 哈尔滨', bg: '📞', set: 'phone',
    cast: [['Lily', '👧', 'f'], ['Tom', '👦', 'm']],
    lines: [
      [0, "Hi, Tom! It's Lily. How's the weather in Harbin?", '嗨，汤姆！我是莉莉。哈尔滨天气怎么样？'],
      [1, "It's snowing! It's very cold.", '正在下雪！很冷。'],
      [0, 'What are you doing?', '你在做什么？'],
      [1, "I'm watching TV with my family. How about Beijing?", '我正在和家人看电视。北京呢？'],
      [0, "It's sunny and warm here.", '这里晴朗暖和。'],
      [1, 'Lucky you!', '你真幸运！'],
    ],
  },
  {
    title: '周末去哪儿了？', place: '星期一早上', bg: '📸', set: 'classroom',
    cast: [['Lily', '👧', 'f'], ['Tom', '👦', 'm']],
    lines: [
      [0, 'How was your weekend, Tom?', '汤姆，你周末过得怎么样？'],
      [1, 'It was great! I went to a farm.', '很棒！我去了一个农场。'],
      [0, 'Did you see any cows?', '你看到奶牛了吗？'],
      [1, 'Yes, I did. I took a lot of photos.', '看到了。我拍了很多照片。'],
      [0, 'Cool! What else did you do?', '酷！你还做了什么？'],
      [1, 'I ate some fresh fruit. What did you do?', '我吃了一些新鲜水果。你做了什么？'],
      [0, 'I visited my grandparents.', '我去看望了我的祖父母。'],
    ],
  },
];
