# 生成一批 Gemini 出图的浏览器动作（给 claude-in-chrome 的 browser_batch 用），并把目标文件名追加进下载队列
# 用法：python tools/mon3d/gembatch.py <起始家族> <结束家族> <这批第一张在本对话里是第几个回复> [--first]
#   --first：新对话的第一条，带完整画风说明（页面里要先跑 gemhelpers.js 定义 __go/__go1 等）
# 每只：发提示词 → 等图出来 → 小截图唤醒渲染 → 把图滚到正中 → 悬停 → 用 JS 聚焦「下载」按钮 → 按回车（真实按键，算用户点击）
import json, sys, re
TAB = int(open('D:/Claude/tools/gem_tab.txt').read().strip())
F = {f['fam']: f for f in json.load(open('art/gemini/families.json', encoding='utf-8'))}
# 撞脸风险大的，换描述（和宝可梦太像的设计）
OVERRIDE = {
    'shyshell': 'Shyshell: a small cute baby-like Water-type round sea snail; sky blue (#80deea) soft body, ice blue (#e0f7fa) face, a big spiral seashell on its back with pink (#f48fb1) spots, two short eye-stalk antennae, a shy small mouth, no legs (it glides on its soft foot). Shyshell closes its shell when people look at it. It opens only for friends.',
    'proudshell': 'Proudshell: a medium-sized, more confident Water/Rock-type big sea snail knight; sky blue (#80deea) soft body with no legs, ice blue (#e0f7fa) face, a huge spiral seashell on its back decorated with crystals and a pink (#f48fb1) star, two eye-stalk antennae wearing a tiny crown between them, a proud smile. NOT a turtle, no arms, no legs. Proudshell is not shy anymore. It shows its shiny shell to everyone.',
    'seasonkid': 'Seasonkid: a small cute baby-like Normal-type round jackalope (a bunny with tiny deer antlers) standing on all fours; tan (#bcaaa4) fur, cream (#fff8e1) belly, long bunny ears, tiny stubby antlers, a round pom-pom tail, green (#81c784) leaf-shaped spots. Its coat changes color with every season. A special stone helps it grow.',
    'springdeer': 'Springdeer: a medium-sized Grass-type jackalope (big rabbit with antlers) standing on all fours; green (#81c784) fur, cream (#f1f8e9) belly, long rabbit ears, branching antlers covered in pink (#f48fb1) cherry blossoms, a pom-pom tail. Flowers open wherever Springdeer walks. It brings spring to cold forests.',
    'summerdeer': 'Summerdeer: a medium-sized Fire-type jackalope (big rabbit with antlers) standing on all fours; coral (#ff8a65) fur, cream (#fff3e0) belly, long rabbit ears with sunny yellow (#ffd54f) tips, antlers shaped like sun rays, a pom-pom tail, a sun-hat. Summerdeer runs across hot fields. Its antlers are warm like summer sun.',
    'autumndeer': 'Autumndeer: a medium-sized Psychic-type jackalope (big rabbit with antlers) standing on all fours; orange (#c9894a) fur, cream (#fff3e0) belly, long rabbit ears, antlers with maple leaves and a small purple (#9c27b0) moon charm, a knitted scarf, a pom-pom tail. Autumndeer looks at the full moon in autumn. Its eyes can see the future.',
    'winterdeer': 'Winterdeer: a medium-sized Ice-type jackalope (big rabbit with antlers) standing on all fours; ice blue (#b3e5fc) fluffy fur, white (#ffffff) belly, long rabbit ears with ear muffs, crystal ice antlers, a snowflake on its chest in sky blue (#4fc3f7), a pom-pom tail. Snow falls quietly when Winterdeer walks by. It sleeps in snowy forests.',
    'aurorakit': "Aurorakit: a small cute baby-like Ice-type round snow hare standing on all fours; gray-blue (#80cbc4) fluffy round body, ice blue (#e0f2f1) belly, SHORT round ears, a round pom-pom tail, a little purple (#ba68c8) knitted scarf, snowflake marks on its cheeks; not fox-like, no neck ruff, no long pointed ears. Aurorakit's tail glows green and purple at night. It loves cold, clear skies.",
    'aurorahare': 'Aurorahare: a medium-sized, more confident Ice/Psychic-type hare standing upright on two legs like a figure skater; gray-blue (#80cbc4) fur, ice blue (#e0f2f1) belly, short round ears with crystal tips, a flowing aurora ribbon sash glowing green and purple (#ba68c8), crystal ice-skate boots, a round pom-pom tail; not fox-like, no neck ruff. When Aurorahare jumps, lights fill the night sky. People travel far to see it.',
    'echobat': 'Echobat: a small cute baby-like Dark/Flying-type round fuzzy bat standing on two small feet; violet (#5e35b1) round body, lavender (#d1c4e9) face, round headphone-like ear muffs instead of pointed ears, small rounded wings, yellow (#ffeb3b) sound-wave stripes on its belly, one tiny fang. Echobat shouts in dark caves. It listens to the echo to find its way.',
    'echowing': 'Echowing: a medium-sized, more confident Dark/Flying-type bat DJ standing on two feet with its wings folded; violet (#5e35b1) body, lavender (#d1c4e9) face, big round studio headphones on its head (no pointed ears), a tail shaped like a microphone, wing membranes with yellow (#ffeb3b) sound-wave patterns, a mask-like marking around its eyes. Echowing can copy any voice it hears. It repeats your words back to you.',
    'joyburst': 'Joyburst: a medium-sized, more confident Fire-type party-popper creature standing upright on two short legs with two small arms; a round coral (#ff8a65) body shaped like a party popper cone, white (#fff5f8) belly, yellow (#ffd54f) confetti-shaped sparks bursting from the top like hair, a star badge on its chest, a huge happy smile, no tail, no lizard features. Joyburst jumps when it is happy. Sparks of joy fly everywhere.',
    'grumpcloud': 'Grumpcloud: a large, powerful Normal/Flying-type chubby thick storm cloud creature standing on two short stubby legs; a big round puffy dark gray (#90a4ae) cloud body with real 3D volume (like a fat round cushion, not flat), a grumpy frown, crossed tiny arms, a few round raindrops hanging below it attached to its body. Grumpcloud rains when it is angry. A kind word makes it smile again.',
    'nibbler': 'Nibbler: a small cute baby-like Normal-type round chipmunk-like creature standing on all fours; tan (#bcaaa4) fur, cream (#efebe9) belly, a big fluffy acorn-shaped tail with brown (#8d6e63) rings, puffy cheeks full of seeds, tiny round ears, no visible big front teeth. Nibbler eats seeds and bread. It is never full.',
    'bigtooth': 'Bigtooth: a medium-sized, more confident Normal-type chunky beaver-like builder standing on all fours; brown (#a1887f) fur, cream (#efebe9) belly, a wide flat paddle tail with dark brown (#6d4c41) criss-cross pattern, a little yellow builder helmet, a tool belt, one small tooth showing. Bigtooth builds dams and bridges. It can cut wood.',
    'buzzbee': 'Buzzbee: a small cute baby-like Electric/Bug-type round fuzzy bumblebee standing on small legs; yellow (#fdd835) fuzz with dark brown (#5d4037) stripes, cream (#fffde7) face, two antennae with tiny glowing bulbs at the tips, small round translucent wings, a short round stinger. Buzzbee makes a loud buzzing sound. Its body has a little electricity.',
    'thunderwing': 'Thunderwing: a medium-sized, more confident Electric/Bug-type dragonfly-like insect standing on four thin legs; orange (#f9a825) body with dark brown (#5d4037) bands, cream (#fff8e1) face, two pairs of long clear dragonfly wings with glowing blue veins, a long segmented straight tail ending in a small round battery-like tip, big compound eyes. Thunderwing flies very fast. Its wings shine in storms.',
    'peeplet': 'Peeplet: a small cute baby-like Normal/Flying-type round chick shaped like a little mail carrier; brown (#a1887f) feathers, cream (#fff3e0) belly, coral (#ff8a65) feet and beak, a tiny postman cap, a small letter bag across its body, a short fan tail attached to its body. Peeplet says peep peep every morning. It wakes up the town.',
    'songwing': 'Songwing: a medium-sized, more confident Normal/Flying-type pigeon-like messenger bird standing on two feet; brown (#8d6e63) feathers, cream (#fff3e0) chest, orange (#ff7043) wing tips, a round postman cap, a mail bag, a short rounded tail attached to its body. Songwing sings beautiful songs. Other birds follow it.',
    'stormhawk': 'Stormhawk: a large, powerful and impressive Normal/Flying-type falcon-like courier bird standing on two feet with its wings folded; dark brown (#6d4c41) feathers, cream (#efebe9) chest, orange (#ff7043) markings like a pilot scarf, aviator goggles on its forehead, a big parcel bag, a solid fan tail attached to its body. Stormhawk flies through any storm. It always delivers on time.',
    'owlet': 'Owlet: a small cute baby-like Psychic-type round fluffy owl chick standing on two feet; brown (#8d6e63) feathers, cream (#efebe9) face, huge round yellow (#ffd54f) glasses-like eye rings, tiny ear tufts, a pencil tucked under one wing. Owlet stays up all night. Its big eyes can see in the dark.',
    'wiseowl': 'Wiseowl: a medium-sized, more confident Psychic/Flying-type tall owl teacher standing on two feet with its wings folded; dark brown (#5d4037) feathers, light gray (#d7ccc8) chest, round yellow (#ffd54f) glasses, a graduation cap with a tassel, holding a small book, a scarf. Wiseowl knows many words. It helps lost children find their way home. (Draw EXACTLY TWO creatures in this image: Owlet and Wiseowl.)',
    'shadowlet': 'Shadowlet: a small cute baby-like Ghost-type sheet-ghost like a child wearing a soft blanket; lavender (#d1c4e9) blanket with purple (#7e57c2) moon patterns, two tiny feet peeking out below, big shy eyes, a small smile, no teeth, no spikes. Shadowlet hides in your shadow. It jumps out and says boo!',
    'nightcloak': 'Nightcloak: a medium-sized, more confident Ghost-type floating cape creature; a purple (#7e57c2) hooded cape with a lavender (#d1c4e9) lining, a round friendly face inside the hood, star-shaped yellow (#ffee58) clasp, the cape hem shaped like soft waves, no teeth, no spikes. Nightcloak looks like a flying cape. It floats over roofs at night.',
    'midnight': 'Midnight: a large, powerful and impressive Ghost/Dark-type night-watch ghost knight floating above the ground; a big round body wrapped in a deep purple (#512da8) cloak with lavender (#d1c4e9) lining, a lantern held in one hand glowing yellow (#ffee58), a moon-shaped helmet crest, calm glowing eyes, a closed calm mouth, no teeth, no spikes on its head. Midnight guards the town at night. Its lantern shows the way home.',
    'ghostship': 'Ghostship: a small cute Ghost/Water-type friendly little ghost pirate ship floating above the ground; a round wooden boat body in dark brown (#6d4c41) with a friendly face on the front, a torn light gray (#d7ccc8) sail with a sky blue (#80deea) wave symbol, a tiny crow nest, a soft ghostly mist under the hull. Ghostship sails on foggy nights. It looks for its lost captain.',
    'frostwing': 'Frostwing: a large majestic legendary Ice/Flying-type round snow owl-like bird standing on two feet with its wings folded; white (#fafafa) fluffy feathers with sky blue (#81d4fa) snowflake patterns, a frosty ice blue scarf around its neck, round calm eyes, short thick legs, a fan tail shaped like a snowflake, no long tail streamers, no crest on its head. Frostwing flies over snowy mountains. Snow falls where it flies.',
    'stormwing': 'Stormwing: a large majestic legendary Electric/Flying-type thunder crane-like bird standing on two long legs with its wings folded; navy (#3949ab) and white feathers, a round rain-cloud shaped crest on its head, yellow (#fdd835) zigzag patterns only on its wing edges, a long elegant neck, a straight fan tail with round tips, no spiky feathers. Stormwing lives in thunder clouds. Its wings make lightning.',
    'blazewing': 'Blazewing: a large majestic legendary Fire/Flying-type sun peacock-like bird standing on two feet with its wings folded; gold (#ffca28) and warm orange (#ff7043) feathers, a round sun-disc shaped fan tail behind it with ember patterns, a small crown of three round feathers, gentle eyes, no fire on its head, no flaming wings. Blazewing sleeps in a volcano. Its feathers glow at night.',
    'bulbling': 'Bulbling: a small cute baby-like Electric-type light bulb creature with tiny stubby feet; a round glass-looking bulb head glowing warm yellow (#fff176) with a friendly face, a gray (#9e9e9e) screw-base body, a curly cord tail with a plug at the end, two tiny arms. Bulbling glows when it is happy. It sleeps in lamps during the day.',
    'lamppost': 'Lamppost: a medium-sized, more confident Electric/Steel-type tall street-lamp creature standing on sturdy iron feet; a slate gray (#607d8b) iron pole body with little arms, a lantern head glowing yellow (#fdd835) with a friendly face, a small round top hat, a curly cord tail with a plug. Lamppost stands by the road all night. It keeps city streets safe and bright.',
    'cakelet': 'Cakelet: a small cute baby-like Normal-type creature that IS a small round strawberry cupcake with tiny stubby feet; pink (#f8bbd0) frosting top, cream (#fff8e1) cup body with ridges, a red (#e53935) strawberry on its head, a friendly face on the cup. Cakelet smells like sweet cake. It appears at birthday parties.',
    'creamcake': 'Creamcake: a medium-sized, more confident Normal-type creature that is a two-layer cream cake standing on two small legs with two small arms; pink (#f48fb1) cream layers, cream (#fff8e1) sponge, red (#e53935) cherries on top, one candle on its head, a friendly face on the front layer. Creamcake makes people smile. Its cream tastes different every day.',
    'cakecastle': 'Cakecastle: a large, powerful and impressive Normal/Psychic-type creature shaped like a big castle made of cake standing on sturdy legs; hot pink (#ec407a) frosting walls, cream (#fff8e1) sponge, tower-shaped candles on top, red strawberries, a friendly face on the front gate. Cakecastle is the biggest cake in the world. It shares slices with everyone.',
    'boltkite': 'Boltkite: a small cute baby-like Electric-type creature shaped like a diamond kite with a round face; yellow (#ffee58) kite body with blue (#42a5f5) cross sticks, two small wing flaps, a long wavy ribbon tail with little bows, tiny feet. Boltkite flies before a storm comes. Its feathers make little sparks.',
    'thunderkite': 'Thunderkite: a medium-sized, more confident Electric/Flying-type big box-kite bird standing on two feet; yellow (#fdd835) kite wings with blue (#1e88e5) frame lines, a round face with goggles, a long ribbon tail with bows, cloud puffs attached to its wings. Thunderkite flies inside storm clouds. It is never afraid of thunder.',
    'jumprope': 'Jumprope: a small cute baby-like Fighting-type round bunny-like athlete standing upright on two legs; orange (#ff7043) fur, cream (#fff3e0) belly, holding a purple (#5c6bc0) jump rope with round wooden handles in both hands, a sweatband on its head. Jumprope jumps a thousand times a day. It never trips.',
    'ropechamp': 'Ropechamp: a medium-sized, more confident Fighting-type kangaroo-like athlete standing upright on two legs; red (#f4511e) fur, cream (#fff3e0) belly, a navy (#3949ab) champion belt, a jump rope around its shoulders, a sweatband, a big grin. Ropechamp wins every game at the sports festival. It never gets tired.',
    'strawhat': 'Strawhat: a small cute baby-like Grass-type friendly scarecrow standing upright on two legs; leaf green (#9ccc65) patchwork overalls, a big golden (#fbc02d) straw hat, straw sticking out of its sleeves, a round cream (#fff9c4) sack face with button eyes and a stitched smile. Strawhat stands in rice fields all summer. It waves to keep birds away.',
    'hotpot': 'Hotpot: a small cute baby-like Fire/Water-type round clay cooking pot creature with tiny stubby feet; red (#e53935) pot body with a sand (#ffe0b2) rim, a lid on its head with a gold (#ffca28) knob, steam curls coming out, two little handle arms, a happy face on the pot. Hotpot is always warm and bubbly. Friends sit around it in winter.',
    'mudcake': 'Mudcake: a small cute baby-like Ground-type round mud pie creature with tiny stubby feet; brown (#8d6e63) mud body shaped like a pie with a crinkled crust edge, small mint (#a5d6a7) leaf sprouts and pebbles on top, a friendly face, little mud-splash hands. Mudcake looks like a pie but it is made of mud. Do not eat it!',
    'skyballoon': 'Skyballoon: a small cute baby-like Fire/Flying-type hot-air balloon creature floating above the ground; a big round orange (#ff7043) balloon head with blue (#42a5f5) vertical stripes and a friendly face, a small woven basket body below it held by ropes, a tiny flame between them. Skyballoon carries travelers over mountains. Hot air keeps it up in the sky.',
    'cinderchick': 'Cinderchick: a small cute baby-like Fire-type round fluffy chick standing on two feet; orange (#ff7043) down feathers, cream (#fff3e0) face, a tiny gold (#ffca28) comb on its head, sitting in half an eggshell like a little bowl, warm ember speckles. Cinderchick has a warm body. It sleeps next to the stove.',
    'sunrooster': 'Sunrooster: a medium-sized, more confident Fire-type farm rooster standing on two feet with its wings folded; orange (#ff7043) feathers, cream (#fff3e0) chest, a big round red comb, a gold (#ffca28) sun-shaped tail fan, a small farmer bandana. Sunrooster sings when the sun comes up. Its song wakes the whole farm.',
    'solarknight': 'Solarknight: a large, powerful and impressive Fire/Fighting-type big proud rooster knight standing on two thick bird legs; orange (#ff7043) feathers, a gold (#ffca28) round sun shield on one wing, a small knight helmet with a red comb plume, a cape, a sun-fan tail, bird feet (not human legs). Solarknight protects the farm. It shines like the morning sun.',
    'cometlet': 'Cometlet: a small cute baby-like Dragon-type round rock-and-ice baby dragon standing on four stubby legs; navy (#3949ab) rocky body with ice blue (#e8eaf6) belly, a small crystal horn, a short tail ending in a sky blue (#80deea) glowing comet puff. Cometlet fell from the sky long ago. Its tail shines like a comet.',
    'cometdrake': 'Cometdrake: a medium-sized, more confident Dragon-type four-legged meteor lizard standing on all fours; navy (#3949ab) rocky plates, ice blue (#e8eaf6) belly, crater patterns, two short crystal horns, a thick tail with a sky blue (#80deea) glowing comet trail, no wings. Cometdrake flies around mountains in circles. It trains every day to reach space.',
    'cometdragon': 'Cometdragon: a large, powerful and impressive Dragon/Flying-type big four-legged meteor dragon standing on sturdy legs; navy (#3949ab) rocky armor with glowing sky blue (#80deea) cracks, ice blue belly, a crown of crystals, short round wings made of crystal plates, a thick tail with a comet trail, calm eyes. Cometdragon rides on falling stars. It brings wishes to the islands.',
    'twirlflame': 'Twirlflame: a small cute baby-like Fire-type spinning-top creature; a round red (#ef5350) toy-top body with cream (#ffebee) and gold (#ffca28) spiral stripes, a friendly face on the top, two tiny arms, a single short peg foot it spins on, a little flame curl on top like a handle, no tail, no animal ears. Twirlflame spins on one foot all day. It leaves circles of fire.',
    'firedancer': 'Firedancer: a medium-sized, more confident Fire-type candle dancer standing upright on two legs; a tall red (#ef5350) wax-candle body with cream (#ffebee) drips, a warm flame on top of its head like hair, a gold (#ffca28) ribbon skirt, long ribbon sleeves, a big smile, no tail, no animal ears. Firedancer dances in the air like a bright flame. Crowds clap for its shows.',
    'lullaby': 'Lullaby: a large majestic legendary Psychic-type tiny floating cloud-sheep; cotton-candy wool in pink (#f8bbd0) and lavender (#d1c4e9), a crescent-moon shaped horn, sleepy half-closed eyes, a ribbon-like tail with a small star at its tip, tiny translucent wings. Lullaby sings children to sleep. Few people have seen it awake.',
    'tidewing': 'Tidewing: a large majestic legendary Psychic/Flying-type sea dragon with a wide manta-ray shaped body, pearl-white (#eceff1) skin with teal (#26a69a) fins and wave stripes, a round friendly face, two long whisker feelers, hovering above the ground. Tidewing sleeps at the bottom of the sea. It wakes up in a storm.',
    'rainbowing': 'Rainbowing: a large majestic legendary Fire/Flying-type peacock-like bird standing on two feet; white body, a fan tail where each long feather is a different rainbow color, a small crown made of tiny clouds, a kind smile. A rainbow follows Rainbowing. It brings good luck.',
    'timesprout': 'Timesprout: a large majestic legendary Psychic/Grass-type small floating seedling spirit; its body is shaped like a green glass hourglass with sand inside, two clock-hand shaped leaves on its head, tiny root feet, big gentle eyes. Timesprout travels through time. Old trees remember its song.',
    'rockgiant': 'Rockgiant: a large majestic legendary Rock-type chunky golem made of stacked round boulders with moss, a single large amber gem in its chest, small glowing eyes under a mossy brow, no dot patterns. Rockgiant sleeps deep in a cave. It is older than the islands.',
    'icegiant': 'Icegiant: a large majestic legendary Ice-type chunky golem made of rounded blue ice blocks with snow on its shoulders, a snowflake-shaped crystal on its chest, friendly round eyes, no dot patterns. Icegiant is made of ice that never melts. It loves cold nights.',
    'irongiant': 'Irongiant: a large majestic legendary Steel-type chunky golem like an old castle gate: riveted iron plates, a round door-knocker ring on its chest, a small horn on its helmet head, glowing yellow eyes, no dot patterns. Irongiant is harder than any metal. It guards an old door.',
    'skysong': 'Skysong: a large majestic legendary Dragon/Psychic-type long ribbon-like wind dragon shaped like a flying kite with silky trailing streamers, peach (#ffccbc) and white body, a musical-note shaped crest, a round cute face, hovering above the ground. Skysong sings with the wind. Its song can calm a storm.',
    'skyecho': 'Skyecho: a large majestic legendary Dragon/Psychic-type sleek dragon shaped like a paper airplane, navy (#3949ab) and white folded-paper body, swept-back paper wings, circular echo rings pattern on its chest, a sharp but friendly face, hovering above the ground. Skyecho repeats every word it hears. It flies faster than a jet.',
    'tidewhale': 'Tidewhale: a large majestic legendary Water-type narwhal-like whale floating just above the ground; pale aqua (#80deea) body with white wave stripes, a spiral seashell crown, a single twisted horn, crystals along its back. Tidewhale can copy any sound. The sea listens to its voice.',
    'wishstar': 'Wishstar: a large majestic legendary Steel/Psychic-type round brass wind-up music-box creature floating in the air; a small wind-up key on its back, a crescent-moon shaped lid on its head, tiny translucent wings, sleepy smile. Wishstar wakes up once in a thousand years. Make a wish!',
    'starcore': 'Starcore: a large majestic legendary Psychic-type floating crystal starfish-like being with five rounded arms, deep blue (#283593) body with golden star speckles, a glowing core in the center with a friendly face. Starcore came from a falling star. It changes its shape.',
    'mindra': 'Mindra: a large majestic legendary Psychic-type creature shaped like a calm sphinx cat lying on a floating cushion of light; four paws, lavender (#b39ddb) fur with ice-blue (#ede7f6) chest, a lotus-flower crown on its head, a glowing violet gem on its forehead, two ribbon-like tails, gentle wise eyes. Mindra can hear your thoughts. It speaks every language.',
    'zappy': 'Zappy: a small cute baby-like Electric-type round chubby hamster standing on four short legs; soft mint-green (#7fd8c4) fur, cream (#fff8e1) belly, small round ears; its tail is a curly coiled cord that ends in a tiny glowing light bulb; whiskers; a friendly smile. Zappy runs fast in the grass. Small sparks jump from its fur.',
    'voltmouse': 'Voltmouse: a medium-sized, more confident Electric-type chubby hamster standing on four legs; teal (#26a69a) fur with a cream (#fff3c4) belly and a fluffy white mane like a cloud; small round ears; its tail is a long coiled cord ending in a bright light bulb; a big grin. Voltmouse has a bright mane. It lights up dark rooms.',
}
args = [a for a in sys.argv[1:] if not a.startswith('--')]
a, b, cnt = map(int, args[:3])
first = '--first' in sys.argv
acts = []
def A(name, **inp):
    inp['tabId'] = TAB; acts.append({'name': name, 'input': inp})
def js(t): A('javascript_tool', action='javascript_exec', text=t)
queue = []
for k in range(a, b + 1):
    f = F[k]; n = len(f['ids'])
    who = f['prompt'].split('\n\n')[-1]
    for id_, txt in OVERRIDE.items():
        who = re.sub(r'(Form \d+: )?' + id_.capitalize() + r': [^\n]*', lambda m: (m.group(1) or '') + txt, who)
    who = who.replace('a lightning-bolt-shaped tail', 'a curly cable tail ending in a round plug (NOT a lightning-bolt shape)')
    fn = '__go1' if (first and k == a) else '__go'
    js('window.%s(%d, %s); "sent %d"' % (fn, n, json.dumps(who, ensure_ascii=True), k))
    for _ in range(3): A('computer', action='wait', duration=10)
    js('await window.__ready(%d)' % cnt)
    A('computer', action='screenshot', scale=0.1)
    js('window.__place()')
    A('computer', action='hover', coordinate=[392, 150])
    js('window.__focusDl()')
    A('computer', action='key', text='Return')
    A('computer', action='wait', duration=2)
    queue.append('D:/Claude/echo-island/art/gemini/fam/%03d.png' % k)
    cnt += 1
open('D:/Claude/tools/gem_next.txt', 'a').write(''.join(q + '\n' for q in queue))
print(json.dumps(acts, ensure_ascii=True))
