// 贴进 Gemini 页面（javascript_tool）定义出图用的小工具；新对话/刷新页面后要重新贴
window.__S = "Original creature design for a kids' monster-collecting adventure game (NOT from any existing franchise; must not resemble any existing Pokemon or other known character). Style: polished 2D game creature illustration, clean cel shading with 2-3 tones, soft rim light, bold dark-brown outline of even weight, rounded friendly shapes, big expressive eyes with highlights, vibrant but not neon colors. IMPORTANT (the art will be turned into 3D models): every creature is drawn FULL BODY, standing on the ground, facing the viewer in a front three-quarter view (body turned about 25 degrees to the viewer's left, face looking at the viewer, both eyes visible), symmetrical relaxed pose, legs and arms clearly separated from the body, chunky round volume (not flat, not a side view), no motion, no action pose. Background plain pure white, no ground plane, no cast shadow, no glow, no sparkles or floating effects, no text, no logo, no border.";
window.__P = 'Generate a new image in exactly the same art style and with the same rules as the first image in this chat (front three-quarter view facing the viewer, full body, chunky 3D-friendly volume, plain white background, no effects, no text, original designs that do not resemble any existing Pokemon).\n\n';
window.__L = n => n === 1 ? 'Draw ONE creature, centered, with plenty of white space around it. Square image.' : 'Draw this evolution family as ' + n + ' separate creatures side by side in one row, from left (first form) to right (final form). They are the same species growing up: each form is bigger and more impressive but keeps the same color scheme and signature features. Leave wide white gaps between them - they must not touch or overlap, and each must be fully visible. Wide landscape image (16:9).';
window.__send = t => { const ed = document.querySelector('rich-textarea .ql-editor'); ed.focus(); ed.innerText = t; ed.dispatchEvent(new Event('input', { bubbles: true })); return new Promise(r => setTimeout(() => { const b = document.querySelector('button.send-button, button[aria-label*="发送"], button[aria-label*="Send"]'); if (b) { b.click(); r('sent'); } else r('no button'); }, 500)); };
window.__go = (n, who) => window.__send(window.__P + window.__L(n) + '\n\n' + who);
window.__go1 = (n, who) => window.__send('Generate an image. ' + window.__S + '\n\n' + window.__L(n) + '\n\n' + who);
window.__ready = async (n) => { for (let i = 0; i < 18; i++) { const rs = document.querySelectorAll('model-response'); const last = rs[rs.length - 1]; const ok = rs.length >= n && last && [...last.querySelectorAll('img')].some(x => x.naturalWidth >= 1000); if (ok) return 'ready ' + rs.length; await new Promise(r => setTimeout(r, 2000)); } return 'TIMEOUT ' + document.querySelectorAll('model-response').length; };
window.__place = (i) => { const rs = document.querySelectorAll('model-response'); const r0 = rs[i == null ? rs.length - 1 : i]; const ims = [...r0.querySelectorAll('img')].filter(x => x.naturalWidth > 200); const im = ims[ims.length - 1]; if (!im) return 'noimg ' + rs.length; im.scrollIntoView({ block: 'center' }); return 'placed ' + rs.length; };
window.__focusDl = (i) => { const rs = document.querySelectorAll('model-response'); const r0 = rs[i == null ? rs.length - 1 : i]; const b = [...r0.querySelectorAll('button')].find(x => /下载|Download/.test(x.getAttribute('aria-label') || '')); if (!b) return 'nobtn'; b.focus(); return 'focused ' + (b.getAttribute('aria-label') || ''); };
'helpers ok';
